In [1]:
import numpy as np

In [2]:
A = np.random.rand(9)
A = A.reshape(3,3)
A = A.T.dot(A)
A

array([[ 1.48712217,  0.59639443,  0.99707583],
       [ 0.59639443,  0.8809259 ,  0.86505913],
       [ 0.99707583,  0.86505913,  1.55315338]])

## The method
The power iteration algorithm starts with a vector $b_0$, which may be an approximation to the dominant eigenvector or a random vector. The method is described by the recurrence relation

$$ b_{k+1} = \frac{Ab_k}{\|Ab_k\|} $$

So, at every iteration, the vector $b_k$ is multiplied by the matrix $A$ and normalized.

If we assume $A$ has an eigenvalue that is strictly greater in magnitude than its other eigenvalues and the starting vector $b_0$ has a nonzero component in the direction of an eigenvector associated with the dominant eigenvalue, then a subsequence $\left( b_{k} \right)$ converges to an eigenvector associated with the dominant eigenvalue.

Without the two assumptions above, the sequence $\left( b_{k} \right)$ does not necessarily converge. 

In [3]:
def power_iteration(A, num_simulations):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    b_k = np.random.rand(A.shape[0])

    for _ in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)

        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k

In [4]:
eig_1 = power_iteration(A, 5)
eig_1

array([ 0.60307139,  0.43749402,  0.66701116])

In [5]:
def orthoganalize_matrix(M, vec):
    T = M.copy()
    for col in range(T.shape[1]):
        T[:, col] -= T[:, col].dot(vec)*vec
    return T

In [6]:
A_1 = orthoganalize_matrix(A, eig_1)
A_1

array([[ 0.38783127, -0.20090956, -0.21855732],
       [-0.20107865,  0.30252716, -0.01681364],
       [-0.2187658 , -0.01677786,  0.20863449]])

In [7]:
eig_2 = power_iteration(A_1, 8)
eig_2

array([ 0.78460364, -0.47615665, -0.3970793 ])

In [12]:
A_2 = orthoganalize_matrix(A_1, eig_2)
A_2

array([[ 0.00580294,  0.03056621, -0.02529424],
       [ 0.03076494,  0.16205021, -0.13410025],
       [-0.02542546, -0.1339252 ,  0.11082616]])

In [13]:
eig_3 = power_iteration(A_2, 10)
eig_3

array([ 0.14388198,  0.76280655, -0.63041585])

In [14]:
eig_1, eig_2, eig_3

(array([ 0.60307139,  0.43749402,  0.66701116]),
 array([ 0.78460364, -0.47615665, -0.3970793 ]),
 array([ 0.14388198,  0.76280655, -0.63041585]))

In [11]:
np.linalg.eig(A)

(array([ 3.02220857,  0.62031383,  0.27867906]),
 array([[ 0.60316005,  0.78465982, -0.14320237],
        [ 0.43744147, -0.47554593, -0.76321755],
        [ 0.66696545, -0.39769968,  0.63007306]]))